from abc import abstractclassmethod

import traci

from trasmapy._IdentifiedObject import IdentifiedObject

class Vehicle(IdentifiedObject):
    def __init__(self, vehicleId : str, personCount : int=0):
        super().__init__(vehicleId)

        self._personCount = personCount

    @abstractclassmethod
    def vehicleClass() -> str:
        return "ignoring"

    @property
    def speed(self) -> float:
        """Returns the speed of the vehicle within the last step (m/s).
        Error value: -2^30"""
        return traci.vehicle.getSpeed(self.id)

    @speed.setter
    def speed(self, newVal: float) -> None:
        """Sets the vehicle speed (m/s). It may drive slower according to the speed mode (safety rules)."""
        if isinstance(newVal, float) or isinstance(newVal, int):
            traci.vehicle.setSpeed(self.id, newVal)
        else:
            raise ValueError("speed needs to be a number (int/float data type).")

    @property
    def lateralSpeed(self) -> float:
        """Returns the lateral speed of the vehicle within the last step (m/s).
        Error value: -2^30"""
        return traci.vehicle.getLateralSpeed(self.id)

    @property
    def acceleration(self) -> float:
        """Returns the acceleration in the previous time step (m/s^2)."""
        return traci.vehicle.getAcceleration(self.id)

    @property
    def edgeId(self) -> str:
        """Returns the ID of the edge the vehicle was in the previous time step."""
        return traci.vehicle.getRoadID(self.id)

    @property
    def laneId(self) -> str:
        """Returns the ID of the lane the vehicle was in the previous time step."""
        return traci.vehicle.getLaneID(self.id)

    @property
    def drivenDistance(self) -> float:
        """Returns the distance the vehicle has already driven (m).
        Error value: -2^30"""
        return traci.vehicle.getDistance(self.id)

    @property
    def CO2Emissions(self) -> float:
        """Returns the vehicle's CO2 emissions during this time step (mg/s).
        To get the value for one step multiply with the step length.
        Error value: -2^30"""
        return traci.vehicle.getCO2Emission(self.id)

    @property
    def COEmissions(self) -> float:
        """Returns the vehicle's CO emissions during this time step (mg/s).
        To get the value for one step multiply with the step length.
        Error value: -2^30"""
        return traci.vehicle.getCOEmission(self.id)

    @property
    def HCEmissions(self) -> float:
        """Returns the vehicle's HC emissions during this time step (mg/s).
        To get the value for one step multiply with the step length.
        Error value: -2^30"""
        return traci.vehicle.getHCEmission(self.id)

    @property
    def PMxEmissions(self) -> float:
        """Returns the vehicle's PMx emissions during this time step (mg/s).
        To get the value for one step multiply with the step length.
        Error value: -2^30"""
        return traci.vehicle.getPMxEmission(self.id)

    @property
    def NOxEmissions(self) -> float:
        """Returns the vehicle's NOx emissions during this time step (mg/s).
        To get the value for one step multiply with the step length.
        Error value: -2^30"""
        return traci.vehicle.getNOxEmission(self.id)

    @property
    def fuelConsumption(self) -> float:
        """Returns the vehicle's NOx emissions during this time step (ml/s).
        To get the value for one step multiply with the step length.
        Error value: -2^30"""
        return traci.vehicle.getFuelConsumption(self.id)

    @property
    def electricityConsumption(self) -> float:
        """Returns the vehicle's electricity consumption during this time step (Wh/s).
        To get the value for one step multiply with the step length.
        Error value: -2^30"""
        return traci.vehicle.getElectricityConsumption(self.id)

    @property
    def noiseEmission(self) -> float:
        """Returns the noise generated by the vehicle (dBA).
        Error value: -2^30"""
        return traci.vehicle.getNoiseEmission(self.id)

    def _getStopState(self) -> int:
        return traci.vehicle.getStopState(self.id)

    def isStopped(self) -> bool:
        """Returns whether the vehicle's stop state is: stopped"""
        return self._getStopState() & 1 != 0

    def isParking(self) -> bool:
        """Returns whether the vehicle's stop state is: parking"""
        return self._getStopState() & 2 != 0

    def isTriggered(self) -> bool:
        """Returns whether the vehicle's stop state is: triggered"""
        return self._getStopState() & 4 != 0

    def isContainerTriggered(self) -> bool:
        """Returns whether the vehicle's stop state is: containerTriggered"""
        return self._getStopState() & 8 != 0

    def isAtBusStop(self) -> bool:
        """Returns whether the vehicle's stop state is: atBusStop"""
        return self._getStopState() & 16 != 0

    def isAtContainerStop(self) -> bool:
        """Returns whether the vehicle's stop state is: atContainerStop"""
        return self._getStopState() & 32 != 0

    def isAtChargingStation(self) -> bool:
        """Returns whether the vehicle's stop state is: atChargingStation"""
        return self._getStopState() & 64 != 0

    def isAtParkingArea(self) -> bool:
        """Returns whether the vehicle's stop state is: atParkingArea"""
        return self._getStopState() & 128 != 0

    def stopFor(self, duration: float, edgeId: str, pos: float = 1) -> None:
        """Stops the vehicle at the given position in the given edge for the given duration (s)."""
        traci.vehicle.setStop(self.id, edgeId, pos, duration=duration)

    def stopUntil(self, until: float, edgeId: str, pos: float = 1) -> None:
        """Stops the vehicle at the given position in the given edge until a given simulation time (s)."""
        traci.vehicle.setStop(self.id, edgeId, pos, until=until)
